name = "my-shunshixuangu"
main = "src/worker.js"
compatibility_date = "2026-09-02"
workers_dev = true
preview_urls = true
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./web"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]
